name: TdZdd test

on:
  push:
    branches: [master, develop]
    paths:
    - '**.cpp'
    - '**.hpp'

jobs:
  test-tdzdd:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: true
    - name: Install dependancies
      run: |
        sudo apt-get install -y make gcc g++
    - name: make
      run: |
        cd src/test
        make test
